import { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./global.css";

export const metadata: Metadata = {
  title: "GitHub User Search App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
        >
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
