name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Prevent duplicate Vercel deploys
        run: |
          if [ "$GITHUB_ACTOR" == "vercel[bot]" ]; then
            echo "Skipping deployment triggered by Vercel auto-deploy"
            exit 0
          fi

      - name: Install Dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy each challenge to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          for challenge in apps/*; do
            if [ -d "$challenge" ]; then
              echo "Deploying $challenge..."
              cd "$challenge" || exit 1
              vercel --token $VERCEL_TOKEN --prod --yes
              cd ../..
            fi
          done
